### ISSUE TITLE
Unable to load *.aseprite file saved with a recent version of Aseprite

### ISSUE THREAD

**Issue by pineapplemachine** [Eiyeron/py_aseprite#5]
I am currently getting this error when trying to load an aseprite file saved using 1.3.6 (via the Steam beta option):

```
{'chunk_size': 22, 'chunk_type': 8199}
{'chunk_size': 106, 'chunk_type': 4}
{'chunk_size': 31, 'chunk_type': 8196}
{'chunk_size': 69, 'chunk_type': 8197}
Traceback (most recent call last):
  File "C:\Users\Sophie\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ase_uv_symmetrize\scratch.py", line 7, in <module>
    ase = AsepriteFile(aseprite_file.read())
  File "C:\Users\Sophie\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ase_uv_symmetrize\aseprite\__init__.py", line 22, in __init__
    self.header, self.frames = AsepriteFile.parse_data(data)
  File "C:\Users\Sophie\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ase_uv_symmetrize\aseprite\__init__.py", line 91, in parse_data
    frame.chunks.append(found_chunk_type(data, data_offset))
  File "C:\Users\Sophie\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ase_uv_symmetrize\aseprite\chunks.py", line 163, in __init__
    (
ValueError: too many values to unpack (expected 2)
```

With a print statement before the exception, I can see that the `cel_struct` tuple value being handled here is `(11, 22, -25480, 99, 1760)`. This corresponds to the drawn layer of the image being loaded here, which is 11 by 22 pixels. I'm not sure what the other three and apparently newly added tuple elements represent. But truncating the tuple to just the first 2 elements did not fix the issue.

When changing L161 of `chunks.py` to this:

```
(
    self.data['width'],
    self.data['height']
) = cel_struct.unpack_from(data, cel_end_offset)[:2]
```

I instead got this error:

```
{'chunk_size': 22, 'chunk_type': 8199}
{'chunk_size': 106, 'chunk_type': 4}
{'chunk_size': 31, 'chunk_type': 8196}
{'chunk_size': 69, 'chunk_type': 8197}
Traceback (most recent call last):
  File "C:\Users\Sophie\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ase_uv_symmetrize\scratch.py", line 7, in <module>
    ase = AsepriteFile(aseprite_file.read())
  File "C:\Users\Sophie\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ase_uv_symmetrize\aseprite\__init__.py", line 22, in __init__
    self.header, self.frames = AsepriteFile.parse_data(data)
  File "C:\Users\Sophie\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ase_uv_symmetrize\aseprite\__init__.py", line 91, in parse_data
    frame.chunks.append(found_chunk_type(data, data_offset))
  File "C:\Users\Sophie\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ase_uv_symmetrize\aseprite\chunks.py", line 167, in __init__
    self.data['data'] = zlib.decompress(data[start_range:end_range])
zlib.error: Error -3 while decompressing data: incorrect header check
```

Aseprite version info:

![image](https://github.com/Eiyeron/py_aseprite/assets/7266412/f1513425-8f78-488e-845b-4cf9a950d332)

![image](https://github.com/Eiyeron/py_aseprite/assets/7266412/fed36dd3-9e47-4e01-a60c-d5477a7b8da2)

An example of an aseprite image file that this is happening with (32x32, indexed color, single layer):

https://files.pineapplemachine.com/public/logs/2024-05-01-test.aseprite

**Comment by pineapplemachine** [comment]
I think I fixed this. It looks as though the wrong struct format was being used for a cel with compressed image data. PR coming shortly.
